//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a text template.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Diagnostics.CodeAnalysis;
using SharpGameInput.Common;

#nullable enable

namespace SharpGameInput.v2
{
    public sealed class GameInputCallbackToken : IDisposable,
        IEquatable<GameInputCallbackToken>
    {
        private IGameInput? _gameInput;
        internal ulong _callbackToken;

        public GameInputCallbackToken(IGameInput gameInput, ulong callbackToken)
        {
            ThrowHelper.CheckNull(gameInput);
            if (callbackToken == 0)
                throw new ArgumentException("The given token is invalid.", nameof(callbackToken));

            _gameInput = gameInput;
            _callbackToken = callbackToken;
        }

        public void Dispose()
        {
            if (_callbackToken != 0)
            {
                // The return value here is ignored, as the only reason false will be returned
                // is if the callback specified by the given token doesn't exist
                _gameInput?.UnregisterCallback(_callbackToken);
                _gameInput = null;
                _callbackToken = 0;
            }
        }

        public void Stop()
        {
            _gameInput?.StopCallback(_callbackToken);
        }

        public static bool operator ==(GameInputCallbackToken? left, GameInputCallbackToken? right)
        {
            if (ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            // GameInput interfaces can be compared directly by pointer for equality
            return left._callbackToken == right._callbackToken;
        }

        public static bool operator !=(GameInputCallbackToken? left, GameInputCallbackToken? right)
            => !(left == right);

        public bool Equals([NotNullWhen(true)] GameInputCallbackToken? obj)
            => this == obj;

        public bool Equals(LightGameInputCallbackToken obj)
            => this == obj;

        public override bool Equals([NotNullWhen(true)] object? obj)
            => obj is GameInputCallbackToken other && Equals(other);

        public override int GetHashCode()
            => _callbackToken.GetHashCode();
    }

    public ref struct LightGameInputCallbackToken
    {
        private readonly IGameInput _gameInput;
        internal readonly ulong _callbackToken;

        public LightGameInputCallbackToken(IGameInput gameInput, ulong callbackToken)
        {
            ThrowHelper.CheckNull(gameInput);
            if (callbackToken == 0)
                throw new ArgumentException("The given token is invalid.", nameof(callbackToken));

            _gameInput = gameInput;
            _callbackToken = callbackToken;
        }

        // Only StopCallback is given functionality here, as it's the
        // only available operation on them when in callbacks according to the docs
        public void Stop()
        {
            _gameInput.StopCallback(_callbackToken);
        }

        public static bool operator ==(LightGameInputCallbackToken left, LightGameInputCallbackToken right)
        {
            return left._callbackToken == right._callbackToken;
        }

        public static bool operator ==(GameInputCallbackToken? left, LightGameInputCallbackToken right)
        {
            return left?._callbackToken == right._callbackToken;
        }

        public static bool operator ==(LightGameInputCallbackToken left, GameInputCallbackToken? right)
        {
            return left._callbackToken == right?._callbackToken;
        }

        public static bool operator !=(LightGameInputCallbackToken left, LightGameInputCallbackToken right)
            => !(left == right);

        public static bool operator !=(GameInputCallbackToken? left, LightGameInputCallbackToken right)
            => !(left == right);

        public static bool operator !=(LightGameInputCallbackToken left, GameInputCallbackToken? right)
            => !(left == right);

        public readonly bool Equals(LightGameInputCallbackToken obj)
            => this == obj;

        public readonly bool Equals(GameInputCallbackToken? obj)
            => this == obj;

#pragma warning disable CS0809 // Obsolete member overrides non-obsolete member
        [Obsolete("Equals(object) on LightGameInputCallbackToken will always throw an exception. Use the equality operator instead.", true)]
        public override bool Equals(object? obj)
            => throw new NotSupportedException();
#pragma warning restore CS0809

        public override int GetHashCode()
            => _callbackToken.GetHashCode();
    }
}
