//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a text template.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.ConstrainedExecution;
using System.Runtime.InteropServices;
using SharpGameInput.Common;

#nullable enable

namespace SharpGameInput.v2
{
    #region Type aliases

    using GameInputCallbackToken_t = uint64_t;
    using HANDLE = IntPtr;
    using HRESULT = int;

    #endregion

    #region Native callback definitions

    using unsafe GameInputReadingCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // reading
        void // <return>
    >;

    using unsafe GameInputDeviceCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        uint64_t, // timestamp
        GameInputDeviceStatus, // currentStatus
        GameInputDeviceStatus, // previousStatus
        void // <return>
    >;

    using unsafe GameInputSystemButtonCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        uint64_t, // timestamp
        GameInputSystemButtons, // currentButtons
        GameInputSystemButtons, // previousButtons
        void // <return>
    >;

    using unsafe GameInputKeyboardLayoutCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        uint64_t, // timestamp
        uint32_t, // currentLayout
        uint32_t, // previousLayout
        void // <return>
    >;

    #endregion

    #region Managed callback definitions

    public delegate void GameInputReadingCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputReading reading
    );

    public delegate void GameInputDeviceCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        uint64_t timestamp,
        GameInputDeviceStatus currentStatus,
        GameInputDeviceStatus previousStatus
    );

    public delegate void GameInputSystemButtonCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        uint64_t timestamp,
        GameInputSystemButtons currentButtons,
        GameInputSystemButtons previousButtons
    );

    public delegate void GameInputKeyboardLayoutCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        uint64_t timestamp,
        uint32_t currentLayout,
        uint32_t previousLayout
    );

    #endregion

    #region Interface definitions

    public abstract class GameInputComPtr : CriticalFinalizerObject,
        IDisposable,
        IEquatable<GameInputComPtr>
    {
        protected internal IntPtr handle;
        private readonly bool ownsHandle;

        public bool IsInvalid => handle == IntPtr.Zero;

        internal GameInputComPtr(IntPtr handle, bool ownsHandle)
        {
            this.handle = handle;
            this.ownsHandle = ownsHandle;
        }

        ~GameInputComPtr() => Dispose(false);

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (disposing)
                DisposeManagedResources();
            DisposeUnmanagedResources();
        }

        protected virtual void DisposeManagedResources()
        {
        }

        protected virtual void DisposeUnmanagedResources()
        {
            if (handle != IntPtr.Zero && ownsHandle)
            {
                Marshal.Release(handle);
                handle = IntPtr.Zero;
            }
        }

        public IntPtr DangerousGetHandle() => handle;

        public static bool operator ==(GameInputComPtr? left, GameInputComPtr? right)
        {
            if (ReferenceEquals(left, right))
                return true;

            if (left is null || right is null)
                return false;

            // GameInput interfaces can be compared directly by pointer for equality
            return left.handle == right.handle;
        }

        public static bool operator !=(GameInputComPtr? left, GameInputComPtr? right)
            => !(left == right);

        public bool Equals([NotNullWhen(true)] GameInputComPtr? ptr)
            => this == ptr;

        public override bool Equals([NotNullWhen(true)] object? obj)
            => obj is GameInputComPtr ptr && Equals(ptr);

        public override int GetHashCode()
            => handle.GetHashCode();
    }

    [Guid("BBAA66D2-837A-40F7-A303-917D500955F4")]
    public sealed unsafe partial class IGameInput : GameInputComPtr,
        IEquatable<IGameInput>
    {
        internal static readonly Guid Iid = new("BBAA66D2-837A-40F7-A303-917D500955F4");

        internal IGameInput(IntPtr handle, bool ownsHandle) : base(handle, ownsHandle) { }

        public IGameInput Duplicate()
        {
            Marshal.AddRef(handle);
            return new(handle, ownsHandle: true);
        }

        public uint64_t GetCurrentTimestamp()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint64_t>)vtable[3];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public HRESULT GetCurrentReading(
            GameInputKind inputKind,
            IGameInputDevice? device,
            out LightIGameInputReading reading
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputKind, IntPtr, out IntPtr, HRESULT>)vtable[4];

            var result = fnPtr(
                thisPtr,
                inputKind,
                device?.DangerousGetHandle() ?? IntPtr.Zero,
                out IntPtr reading_handle
            );

            reading = new(reading_handle, ownsHandle: true);
            return result;
        }

        public HRESULT GetNextReading(
            LightIGameInputReading referenceReading,
            GameInputKind inputKind,
            IGameInputDevice? device,
            out LightIGameInputReading reading
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));
            ThrowHelper.CheckDisposed(referenceReading.IsInvalid, typeof(LightIGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, IntPtr, GameInputKind, IntPtr, out IntPtr, HRESULT>)vtable[5];

            var result = fnPtr(
                thisPtr,
                referenceReading.DangerousGetHandle(),
                inputKind,
                device?.DangerousGetHandle() ?? IntPtr.Zero,
                out IntPtr reading_handle
            );

            reading = new(reading_handle, ownsHandle: true);
            return result;
        }

        public HRESULT GetPreviousReading(
            LightIGameInputReading referenceReading,
            GameInputKind inputKind,
            IGameInputDevice? device,
            out LightIGameInputReading reading
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));
            ThrowHelper.CheckDisposed(referenceReading.IsInvalid, typeof(LightIGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, IntPtr, GameInputKind, IntPtr, out IntPtr, HRESULT>)vtable[6];

            var result = fnPtr(
                thisPtr,
                referenceReading.DangerousGetHandle(),
                inputKind,
                device?.DangerousGetHandle() ?? IntPtr.Zero,
                out IntPtr reading_handle
            );

            reading = new(reading_handle, ownsHandle: true);
            return result;
        }

        private HRESULT _RegisterReadingCallback(
            IGameInputDevice? device,
            GameInputKind inputKind,
            void* context,
            GameInputReadingCallback_NativePtr callbackFunc,
            out GameInputCallbackToken_t callbackToken
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, IntPtr, GameInputKind, void*, GameInputReadingCallback_NativePtr, out GameInputCallbackToken_t, HRESULT>)vtable[7];

            var result = fnPtr(
                thisPtr,
                device?.DangerousGetHandle() ?? IntPtr.Zero,
                inputKind,
                context,
                callbackFunc,
                out callbackToken
            );

            return result;
        }

        private HRESULT _RegisterDeviceCallback(
            IGameInputDevice? device,
            GameInputKind inputKind,
            GameInputDeviceStatus statusFilter,
            GameInputEnumerationKind enumerationKind,
            void* context,
            GameInputDeviceCallback_NativePtr callbackFunc,
            out GameInputCallbackToken_t callbackToken
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, IntPtr, GameInputKind, GameInputDeviceStatus, GameInputEnumerationKind, void*, GameInputDeviceCallback_NativePtr, out GameInputCallbackToken_t, HRESULT>)vtable[8];

            var result = fnPtr(
                thisPtr,
                device?.DangerousGetHandle() ?? IntPtr.Zero,
                inputKind,
                statusFilter,
                enumerationKind,
                context,
                callbackFunc,
                out callbackToken
            );

            return result;
        }

        private HRESULT _RegisterSystemButtonCallback(
            IGameInputDevice? device,
            GameInputSystemButtons buttonFilter,
            void* context,
            GameInputSystemButtonCallback_NativePtr callbackFunc,
            out GameInputCallbackToken_t callbackToken
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, IntPtr, GameInputSystemButtons, void*, GameInputSystemButtonCallback_NativePtr, out GameInputCallbackToken_t, HRESULT>)vtable[9];

            var result = fnPtr(
                thisPtr,
                device?.DangerousGetHandle() ?? IntPtr.Zero,
                buttonFilter,
                context,
                callbackFunc,
                out callbackToken
            );

            return result;
        }

        private HRESULT _RegisterKeyboardLayoutCallback(
            IGameInputDevice? device,
            void* context,
            GameInputKeyboardLayoutCallback_NativePtr callbackFunc,
            out GameInputCallbackToken_t callbackToken
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, IntPtr, void*, GameInputKeyboardLayoutCallback_NativePtr, out GameInputCallbackToken_t, HRESULT>)vtable[10];

            var result = fnPtr(
                thisPtr,
                device?.DangerousGetHandle() ?? IntPtr.Zero,
                context,
                callbackFunc,
                out callbackToken
            );

            return result;
        }

        internal void StopCallback(
            GameInputCallbackToken_t callbackToken
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputCallbackToken_t, void>)vtable[11];

            fnPtr(
                thisPtr,
                callbackToken
            );

        }

        private bool _UnregisterCallback(
            GameInputCallbackToken_t callbackToken
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputCallbackToken_t, byte>)vtable[12];

            var result = fnPtr(
                thisPtr,
                callbackToken
            );

            return result != 0;
        }

        public HRESULT CreateDispatcher(
            out IGameInputDispatcher dispatcher
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out IntPtr, HRESULT>)vtable[13];

            var result = fnPtr(
                thisPtr,
                out IntPtr dispatcher_handle
            );

            dispatcher = new(dispatcher_handle, ownsHandle: true);
            return result;
        }

        public HRESULT FindDeviceFromId(
            in APP_LOCAL_DEVICE_ID value,
            out IGameInputDevice device
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, in APP_LOCAL_DEVICE_ID, out IntPtr, HRESULT>)vtable[14];

            var result = fnPtr(
                thisPtr,
                in value,
                out IntPtr device_handle
            );

            device = new(device_handle, ownsHandle: true);
            return result;
        }

        public HRESULT FindDeviceFromPlatformString(
            wchar_t* value,
            out IGameInputDevice device
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));
            ThrowHelper.CheckNull(value);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, wchar_t*, out IntPtr, HRESULT>)vtable[15];

            var result = fnPtr(
                thisPtr,
                value,
                out IntPtr device_handle
            );

            device = new(device_handle, ownsHandle: true);
            return result;
        }

        public HRESULT FindDeviceFromPlatformString(string value, out IGameInputDevice device)
        {
            fixed (char* ptr = value)
            {
                return FindDeviceFromPlatformString(ptr, out device);
            }
        }

        public void SetFocusPolicy(
            GameInputFocusPolicy policy
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInput));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputFocusPolicy, void>)vtable[16];

            fnPtr(
                thisPtr,
                policy
            );

        }

        public bool Equals([NotNullWhen(true)] IGameInput? ptr)
            => this == ptr;
    }

    [Guid("65F06483-DB76-40B7-B745-F591FAE55FC9")]
    public sealed unsafe partial class IGameInputReading : GameInputComPtr,
        IEquatable<IGameInputReading>
    {
        internal static readonly Guid Iid = new("65F06483-DB76-40B7-B745-F591FAE55FC9");

        internal IGameInputReading(IntPtr handle, bool ownsHandle) : base(handle, ownsHandle) { }

        public IGameInputReading Duplicate()
        {
            Marshal.AddRef(handle);
            return new(handle, ownsHandle: true);
        }

        public GameInputKind GetInputKind()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputKind>)vtable[3];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint64_t GetTimestamp()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint64_t>)vtable[4];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        private void GetDevice(
            out LightIGameInputDevice device
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out IntPtr, void>)vtable[5];

            fnPtr(
                thisPtr,
                out IntPtr device_handle
            );

            device = new(device_handle, ownsHandle: true);
        }

        public LightIGameInputDevice GetDevice()
        {
            GetDevice(out var device);
            return device;
        }

        public uint32_t GetControllerAxisCount()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[6];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint32_t GetControllerAxisState(
            uint32_t stateArrayCount,
            float* stateArray
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));
            ThrowHelper.CheckNull(stateArray);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, float*, uint32_t>)vtable[7];

            var result = fnPtr(
                thisPtr,
                stateArrayCount,
                stateArray
            );

            return result;
        }

        public uint32_t GetControllerAxisState(
            float[] stateArray
        )
        {
            fixed (float* stateArrayPtr = stateArray)
            {
                return GetControllerAxisState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public uint32_t GetControllerAxisState(
            scoped Span<float> stateArray
        )
        {
            fixed (float* stateArrayPtr = stateArray)
            {
                return GetControllerAxisState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }
#endif

        public uint32_t GetControllerButtonCount()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[8];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint32_t GetControllerButtonState(
            uint32_t stateArrayCount,
            ByteBool* stateArray
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));
            ThrowHelper.CheckNull(stateArray);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, ByteBool*, uint32_t>)vtable[9];

            var result = fnPtr(
                thisPtr,
                stateArrayCount,
                stateArray
            );

            return result;
        }

        public uint32_t GetControllerButtonState(
            ByteBool[] stateArray
        )
        {
            fixed (ByteBool* stateArrayPtr = stateArray)
            {
                return GetControllerButtonState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public uint32_t GetControllerButtonState(
            scoped Span<ByteBool> stateArray
        )
        {
            fixed (ByteBool* stateArrayPtr = stateArray)
            {
                return GetControllerButtonState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }
#endif

        public uint32_t GetControllerSwitchCount()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[10];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint32_t GetControllerSwitchState(
            uint32_t stateArrayCount,
            GameInputSwitchPosition* stateArray
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));
            ThrowHelper.CheckNull(stateArray);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, GameInputSwitchPosition*, uint32_t>)vtable[11];

            var result = fnPtr(
                thisPtr,
                stateArrayCount,
                stateArray
            );

            return result;
        }

        public uint32_t GetControllerSwitchState(
            GameInputSwitchPosition[] stateArray
        )
        {
            fixed (GameInputSwitchPosition* stateArrayPtr = stateArray)
            {
                return GetControllerSwitchState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public uint32_t GetControllerSwitchState(
            scoped Span<GameInputSwitchPosition> stateArray
        )
        {
            fixed (GameInputSwitchPosition* stateArrayPtr = stateArray)
            {
                return GetControllerSwitchState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }
#endif

        public uint32_t GetKeyCount()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[12];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint32_t GetKeyState(
            uint32_t stateArrayCount,
            GameInputKeyState* stateArray
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));
            ThrowHelper.CheckNull(stateArray);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, GameInputKeyState*, uint32_t>)vtable[13];

            var result = fnPtr(
                thisPtr,
                stateArrayCount,
                stateArray
            );

            return result;
        }

        public uint32_t GetKeyState(
            GameInputKeyState[] stateArray
        )
        {
            fixed (GameInputKeyState* stateArrayPtr = stateArray)
            {
                return GetKeyState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public uint32_t GetKeyState(
            scoped Span<GameInputKeyState> stateArray
        )
        {
            fixed (GameInputKeyState* stateArrayPtr = stateArray)
            {
                return GetKeyState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }
#endif

        public bool GetMouseState(
            out GameInputMouseState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputMouseState, byte>)vtable[14];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetSensorsState(
            out GameInputSensorsState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputSensorsState, byte>)vtable[15];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetArcadeStickState(
            out GameInputArcadeStickState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputArcadeStickState, byte>)vtable[16];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetFlightStickState(
            out GameInputFlightStickState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputFlightStickState, byte>)vtable[17];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetGamepadState(
            out GameInputGamepadState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputGamepadState, byte>)vtable[18];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetRacingWheelState(
            out GameInputRacingWheelState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputRacingWheelState, byte>)vtable[19];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetUiNavigationState(
            out GameInputUiNavigationState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputUiNavigationState, byte>)vtable[20];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool Equals([NotNullWhen(true)] IGameInputReading? ptr)
            => this == ptr;

        public bool Equals(LightIGameInputReading obj)
            => this == obj;
    }

    public unsafe ref partial struct LightIGameInputReading
    {
        internal IntPtr handle;
        private bool ownsHandle;

        public bool IsInvalid => handle == IntPtr.Zero;

        internal LightIGameInputReading(IntPtr handle, bool ownsHandle)
        {
            this.handle = handle;
            this.ownsHandle = ownsHandle;
        }

        public void Dispose()
        {
            if (handle != IntPtr.Zero && ownsHandle)
            {
                Marshal.Release(handle);
                handle = IntPtr.Zero;
            }
        }

        public IntPtr DangerousGetHandle() => handle;

        public IGameInputReading ToComPtr()
        {
            // Move handle to the new instance
            var handle = this.handle;
            this.handle = IntPtr.Zero;
            return new(handle, ownsHandle);
        }

        public static implicit operator LightIGameInputReading(IGameInputReading instance)
        {
            return new(instance.DangerousGetHandle(), ownsHandle: false);
        }

        public static bool operator ==(LightIGameInputReading left, LightIGameInputReading right)
        {
            // GameInput interfaces can be compared directly by pointer for equality
            return left.handle == right.handle;
        }

        public static bool operator ==(IGameInputReading? left, LightIGameInputReading right)
        {
            return left?.handle == right.handle;
        }

        public static bool operator ==(LightIGameInputReading left, IGameInputReading? right)
        {
            return left.handle == right?.handle;
        }

        public static bool operator !=(LightIGameInputReading left, LightIGameInputReading right)
            => !(left == right);

        public static bool operator !=(IGameInputReading? left, LightIGameInputReading right)
            => !(left == right);

        public static bool operator !=(LightIGameInputReading left, IGameInputReading? right)
            => !(left == right);

        public readonly bool Equals(LightIGameInputReading obj)
            => this == obj;

        public readonly bool Equals(IGameInputReading? obj)
            => this == obj;

#pragma warning disable CS0809 // Obsolete member overrides non-obsolete member
        [Obsolete("Equals(object) on LightIGameInputReading will always throw an exception. Use the equality operator instead.", true)]
        public override bool Equals(object? obj)
            => throw new NotSupportedException();
#pragma warning restore CS0809

        public override int GetHashCode()
            => handle.GetHashCode();

        public GameInputKind GetInputKind()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputKind>)vtable[3];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint64_t GetTimestamp()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint64_t>)vtable[4];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        private void GetDevice(
            out LightIGameInputDevice device
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out IntPtr, void>)vtable[5];

            fnPtr(
                thisPtr,
                out IntPtr device_handle
            );

            device = new(device_handle, ownsHandle: true);
        }

        public LightIGameInputDevice GetDevice()
        {
            GetDevice(out var device);
            return device;
        }

        public uint32_t GetControllerAxisCount()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[6];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint32_t GetControllerAxisState(
            uint32_t stateArrayCount,
            float* stateArray
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));
            ThrowHelper.CheckNull(stateArray);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, float*, uint32_t>)vtable[7];

            var result = fnPtr(
                thisPtr,
                stateArrayCount,
                stateArray
            );

            return result;
        }

        public uint32_t GetControllerAxisState(
            float[] stateArray
        )
        {
            fixed (float* stateArrayPtr = stateArray)
            {
                return GetControllerAxisState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public uint32_t GetControllerAxisState(
            scoped Span<float> stateArray
        )
        {
            fixed (float* stateArrayPtr = stateArray)
            {
                return GetControllerAxisState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }
#endif

        public uint32_t GetControllerButtonCount()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[8];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint32_t GetControllerButtonState(
            uint32_t stateArrayCount,
            ByteBool* stateArray
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));
            ThrowHelper.CheckNull(stateArray);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, ByteBool*, uint32_t>)vtable[9];

            var result = fnPtr(
                thisPtr,
                stateArrayCount,
                stateArray
            );

            return result;
        }

        public uint32_t GetControllerButtonState(
            ByteBool[] stateArray
        )
        {
            fixed (ByteBool* stateArrayPtr = stateArray)
            {
                return GetControllerButtonState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public uint32_t GetControllerButtonState(
            scoped Span<ByteBool> stateArray
        )
        {
            fixed (ByteBool* stateArrayPtr = stateArray)
            {
                return GetControllerButtonState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }
#endif

        public uint32_t GetControllerSwitchCount()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[10];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint32_t GetControllerSwitchState(
            uint32_t stateArrayCount,
            GameInputSwitchPosition* stateArray
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));
            ThrowHelper.CheckNull(stateArray);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, GameInputSwitchPosition*, uint32_t>)vtable[11];

            var result = fnPtr(
                thisPtr,
                stateArrayCount,
                stateArray
            );

            return result;
        }

        public uint32_t GetControllerSwitchState(
            GameInputSwitchPosition[] stateArray
        )
        {
            fixed (GameInputSwitchPosition* stateArrayPtr = stateArray)
            {
                return GetControllerSwitchState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public uint32_t GetControllerSwitchState(
            scoped Span<GameInputSwitchPosition> stateArray
        )
        {
            fixed (GameInputSwitchPosition* stateArrayPtr = stateArray)
            {
                return GetControllerSwitchState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }
#endif

        public uint32_t GetKeyCount()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[12];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public uint32_t GetKeyState(
            uint32_t stateArrayCount,
            GameInputKeyState* stateArray
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));
            ThrowHelper.CheckNull(stateArray);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, GameInputKeyState*, uint32_t>)vtable[13];

            var result = fnPtr(
                thisPtr,
                stateArrayCount,
                stateArray
            );

            return result;
        }

        public uint32_t GetKeyState(
            GameInputKeyState[] stateArray
        )
        {
            fixed (GameInputKeyState* stateArrayPtr = stateArray)
            {
                return GetKeyState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public uint32_t GetKeyState(
            scoped Span<GameInputKeyState> stateArray
        )
        {
            fixed (GameInputKeyState* stateArrayPtr = stateArray)
            {
                return GetKeyState(
                    (uint32_t)stateArray.Length,
                    stateArrayPtr
                );
            }
        }
#endif

        public bool GetMouseState(
            out GameInputMouseState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputMouseState, byte>)vtable[14];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetSensorsState(
            out GameInputSensorsState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputSensorsState, byte>)vtable[15];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetArcadeStickState(
            out GameInputArcadeStickState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputArcadeStickState, byte>)vtable[16];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetFlightStickState(
            out GameInputFlightStickState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputFlightStickState, byte>)vtable[17];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetGamepadState(
            out GameInputGamepadState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputGamepadState, byte>)vtable[18];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetRacingWheelState(
            out GameInputRacingWheelState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputRacingWheelState, byte>)vtable[19];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }

        public bool GetUiNavigationState(
            out GameInputUiNavigationState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputReading));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputUiNavigationState, byte>)vtable[20];

            var result = fnPtr(
                thisPtr,
                out state
            );

            return result != 0;
        }
    }

    [Guid("39A0C9F2-F055-4089-96E7-25B2756D3077")]
    public sealed unsafe partial class IGameInputDevice : GameInputComPtr,
        IEquatable<IGameInputDevice>
    {
        internal static readonly Guid Iid = new("39A0C9F2-F055-4089-96E7-25B2756D3077");

        internal IGameInputDevice(IntPtr handle, bool ownsHandle) : base(handle, ownsHandle) { }

        public IGameInputDevice Duplicate()
        {
            Marshal.AddRef(handle);
            return new(handle, ownsHandle: true);
        }

        public HRESULT GetDeviceInfo(
            out GameInputDeviceInfo* info
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputDeviceInfo*, HRESULT>)vtable[3];

            var result = fnPtr(
                thisPtr,
                out info
            );

            return result;
        }

        /// <remarks>
        /// Convenience overload to avoid unsafe code requirement.
        /// Will throw if <see cref="GetDeviceInfo(out GameInputDeviceInfo*)"/> returns an error!
        /// </remarks>
        public ref readonly GameInputDeviceInfo GetDeviceInfo()
        {
            var result = GetDeviceInfo(out var info);
            if (result < 0)
            {
                throw new Exception($"Failed to get device info: 0x{result:X8}");
            }

            return ref *info;
        }

        public HRESULT GetHapticInfo(
            out GameInputHapticInfo info
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputHapticInfo, HRESULT>)vtable[4];

            var result = fnPtr(
                thisPtr,
                out info
            );

            return result;
        }

        public GameInputDeviceStatus GetDeviceStatus()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputDeviceStatus>)vtable[5];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public HRESULT CreateForceFeedbackEffect(
            uint32_t motorIndex,
            in GameInputForceFeedbackParams ffbParams,
            out LightIGameInputForceFeedbackEffect effect
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, in GameInputForceFeedbackParams, out IntPtr, HRESULT>)vtable[6];

            var result = fnPtr(
                thisPtr,
                motorIndex,
                in ffbParams,
                out IntPtr effect_handle
            );

            effect = new(effect_handle, ownsHandle: true);
            return result;
        }

        public bool IsForceFeedbackMotorPoweredOn(
            uint32_t motorIndex
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, byte>)vtable[7];

            var result = fnPtr(
                thisPtr,
                motorIndex
            );

            return result != 0;
        }

        public void SetForceFeedbackMotorGain(
            uint32_t motorIndex,
            float masterGain
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, float, void>)vtable[8];

            fnPtr(
                thisPtr,
                motorIndex,
                masterGain
            );

        }

        public void SetRumbleState(
            in GameInputRumbleParams rumbleParams
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, in GameInputRumbleParams, void>)vtable[9];

            fnPtr(
                thisPtr,
                in rumbleParams
            );

        }

        public HRESULT DirectInputEscape(
            uint32_t command,
            void* bufferIn,
            uint32_t bufferInSize,
            void* bufferOut,
            uint32_t bufferOutSize,
            out uint32_t bufferOutSizeWritten
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));
            ThrowHelper.CheckNull(bufferIn);
            ThrowHelper.CheckNull(bufferOut);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, void*, uint32_t, void*, uint32_t, out uint32_t, HRESULT>)vtable[10];

            var result = fnPtr(
                thisPtr,
                command,
                bufferIn,
                bufferInSize,
                bufferOut,
                bufferOutSize,
                out bufferOutSizeWritten
            );

            return result;
        }

        public HRESULT DirectInputEscape(
            uint32_t command,
            byte[]? bufferIn,
            byte[]? bufferOut,
            out uint32_t bufferOutSizeWritten
        )
        {
            fixed (byte* bufferInPtr = bufferIn)
            fixed (byte* bufferOutPtr = bufferOut)
            {
                return DirectInputEscape(
                    command,
                    bufferInPtr,
                    (uint32_t)(bufferIn?.Length ?? 0),
                    bufferOutPtr,
                    (uint32_t)(bufferOut?.Length ?? 0),
                    out bufferOutSizeWritten
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public HRESULT DirectInputEscape(
            uint32_t command,
            scoped ReadOnlySpan<byte> bufferIn,
            scoped Span<byte> bufferOut,
            out uint32_t bufferOutSizeWritten
        )
        {
            fixed (byte* bufferInPtr = bufferIn)
            fixed (byte* bufferOutPtr = bufferOut)
            {
                return DirectInputEscape(
                    command,
                    bufferInPtr,
                    (uint32_t)bufferIn.Length,
                    bufferOutPtr,
                    (uint32_t)bufferOut.Length,
                    out bufferOutSizeWritten
                );
            }
        }
#endif

        public HRESULT DirectInputEscape<TIn>(
            uint32_t command,
            in TIn input
        )
            where TIn : unmanaged
        {
            fixed (TIn* inputPtr = &input)
            {
                return DirectInputEscape(
                    command,
                    inputPtr, (uint32_t)sizeof(TIn),
                    null, 0,
                    out _
                );
            }
        }

        public HRESULT DirectInputEscape<TOut>(
            uint32_t command,
            out TOut output,
            out uint32_t bytesReturned
        )
            where TOut : unmanaged
        {
            fixed (TOut* outputPtr = &output)
            {
                return DirectInputEscape(
                    command,
                    null, 0,
                    outputPtr, (uint32_t)sizeof(TOut),
                    out bytesReturned
                );
            }
        }

        public HRESULT DirectInputEscape<TIn, TOut>(
            uint32_t command,
            in TIn input,
            out TOut output,
            out uint32_t bytesReturned
        )
            where TIn : unmanaged
            where TOut : unmanaged
        {
            fixed (TIn* inputPtr = &input)
            fixed (TOut* outputPtr = &output)
            {
                return DirectInputEscape(
                    command,
                    inputPtr, (uint32_t)sizeof(TIn),
                    outputPtr, (uint32_t)sizeof(TOut),
                    out bytesReturned
                );
            }
        }

        public bool Equals([NotNullWhen(true)] IGameInputDevice? ptr)
            => this == ptr;

        public bool Equals(LightIGameInputDevice obj)
            => this == obj;
    }

    public unsafe ref partial struct LightIGameInputDevice
    {
        internal IntPtr handle;
        private bool ownsHandle;

        public bool IsInvalid => handle == IntPtr.Zero;

        internal LightIGameInputDevice(IntPtr handle, bool ownsHandle)
        {
            this.handle = handle;
            this.ownsHandle = ownsHandle;
        }

        public void Dispose()
        {
            if (handle != IntPtr.Zero && ownsHandle)
            {
                Marshal.Release(handle);
                handle = IntPtr.Zero;
            }
        }

        public IntPtr DangerousGetHandle() => handle;

        public IGameInputDevice ToComPtr()
        {
            // Move handle to the new instance
            var handle = this.handle;
            this.handle = IntPtr.Zero;
            return new(handle, ownsHandle);
        }

        public static implicit operator LightIGameInputDevice(IGameInputDevice instance)
        {
            return new(instance.DangerousGetHandle(), ownsHandle: false);
        }

        public static bool operator ==(LightIGameInputDevice left, LightIGameInputDevice right)
        {
            // GameInput interfaces can be compared directly by pointer for equality
            return left.handle == right.handle;
        }

        public static bool operator ==(IGameInputDevice? left, LightIGameInputDevice right)
        {
            return left?.handle == right.handle;
        }

        public static bool operator ==(LightIGameInputDevice left, IGameInputDevice? right)
        {
            return left.handle == right?.handle;
        }

        public static bool operator !=(LightIGameInputDevice left, LightIGameInputDevice right)
            => !(left == right);

        public static bool operator !=(IGameInputDevice? left, LightIGameInputDevice right)
            => !(left == right);

        public static bool operator !=(LightIGameInputDevice left, IGameInputDevice? right)
            => !(left == right);

        public readonly bool Equals(LightIGameInputDevice obj)
            => this == obj;

        public readonly bool Equals(IGameInputDevice? obj)
            => this == obj;

#pragma warning disable CS0809 // Obsolete member overrides non-obsolete member
        [Obsolete("Equals(object) on LightIGameInputDevice will always throw an exception. Use the equality operator instead.", true)]
        public override bool Equals(object? obj)
            => throw new NotSupportedException();
#pragma warning restore CS0809

        public override int GetHashCode()
            => handle.GetHashCode();

        public HRESULT GetDeviceInfo(
            out GameInputDeviceInfo* info
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputDeviceInfo*, HRESULT>)vtable[3];

            var result = fnPtr(
                thisPtr,
                out info
            );

            return result;
        }

        /// <remarks>
        /// Convenience overload to avoid unsafe code requirement.
        /// Will throw if <see cref="GetDeviceInfo(out GameInputDeviceInfo*)"/> returns an error!
        /// </remarks>
        public ref readonly GameInputDeviceInfo GetDeviceInfo()
        {
            var result = GetDeviceInfo(out var info);
            if (result < 0)
            {
                throw new Exception($"Failed to get device info: 0x{result:X8}");
            }

            return ref *info;
        }

        public HRESULT GetHapticInfo(
            out GameInputHapticInfo info
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputHapticInfo, HRESULT>)vtable[4];

            var result = fnPtr(
                thisPtr,
                out info
            );

            return result;
        }

        public GameInputDeviceStatus GetDeviceStatus()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputDeviceStatus>)vtable[5];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public HRESULT CreateForceFeedbackEffect(
            uint32_t motorIndex,
            in GameInputForceFeedbackParams ffbParams,
            out LightIGameInputForceFeedbackEffect effect
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, in GameInputForceFeedbackParams, out IntPtr, HRESULT>)vtable[6];

            var result = fnPtr(
                thisPtr,
                motorIndex,
                in ffbParams,
                out IntPtr effect_handle
            );

            effect = new(effect_handle, ownsHandle: true);
            return result;
        }

        public bool IsForceFeedbackMotorPoweredOn(
            uint32_t motorIndex
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, byte>)vtable[7];

            var result = fnPtr(
                thisPtr,
                motorIndex
            );

            return result != 0;
        }

        public void SetForceFeedbackMotorGain(
            uint32_t motorIndex,
            float masterGain
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, float, void>)vtable[8];

            fnPtr(
                thisPtr,
                motorIndex,
                masterGain
            );

        }

        public void SetRumbleState(
            in GameInputRumbleParams rumbleParams
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, in GameInputRumbleParams, void>)vtable[9];

            fnPtr(
                thisPtr,
                in rumbleParams
            );

        }

        public HRESULT DirectInputEscape(
            uint32_t command,
            void* bufferIn,
            uint32_t bufferInSize,
            void* bufferOut,
            uint32_t bufferOutSize,
            out uint32_t bufferOutSizeWritten
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDevice));
            ThrowHelper.CheckNull(bufferIn);
            ThrowHelper.CheckNull(bufferOut);

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t, void*, uint32_t, void*, uint32_t, out uint32_t, HRESULT>)vtable[10];

            var result = fnPtr(
                thisPtr,
                command,
                bufferIn,
                bufferInSize,
                bufferOut,
                bufferOutSize,
                out bufferOutSizeWritten
            );

            return result;
        }

        public HRESULT DirectInputEscape(
            uint32_t command,
            byte[]? bufferIn,
            byte[]? bufferOut,
            out uint32_t bufferOutSizeWritten
        )
        {
            fixed (byte* bufferInPtr = bufferIn)
            fixed (byte* bufferOutPtr = bufferOut)
            {
                return DirectInputEscape(
                    command,
                    bufferInPtr,
                    (uint32_t)(bufferIn?.Length ?? 0),
                    bufferOutPtr,
                    (uint32_t)(bufferOut?.Length ?? 0),
                    out bufferOutSizeWritten
                );
            }
        }

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
        public HRESULT DirectInputEscape(
            uint32_t command,
            scoped ReadOnlySpan<byte> bufferIn,
            scoped Span<byte> bufferOut,
            out uint32_t bufferOutSizeWritten
        )
        {
            fixed (byte* bufferInPtr = bufferIn)
            fixed (byte* bufferOutPtr = bufferOut)
            {
                return DirectInputEscape(
                    command,
                    bufferInPtr,
                    (uint32_t)bufferIn.Length,
                    bufferOutPtr,
                    (uint32_t)bufferOut.Length,
                    out bufferOutSizeWritten
                );
            }
        }
#endif

        public HRESULT DirectInputEscape<TIn>(
            uint32_t command,
            in TIn input
        )
            where TIn : unmanaged
        {
            fixed (TIn* inputPtr = &input)
            {
                return DirectInputEscape(
                    command,
                    inputPtr, (uint32_t)sizeof(TIn),
                    null, 0,
                    out _
                );
            }
        }

        public HRESULT DirectInputEscape<TOut>(
            uint32_t command,
            out TOut output,
            out uint32_t bytesReturned
        )
            where TOut : unmanaged
        {
            fixed (TOut* outputPtr = &output)
            {
                return DirectInputEscape(
                    command,
                    null, 0,
                    outputPtr, (uint32_t)sizeof(TOut),
                    out bytesReturned
                );
            }
        }

        public HRESULT DirectInputEscape<TIn, TOut>(
            uint32_t command,
            in TIn input,
            out TOut output,
            out uint32_t bytesReturned
        )
            where TIn : unmanaged
            where TOut : unmanaged
        {
            fixed (TIn* inputPtr = &input)
            fixed (TOut* outputPtr = &output)
            {
                return DirectInputEscape(
                    command,
                    inputPtr, (uint32_t)sizeof(TIn),
                    outputPtr, (uint32_t)sizeof(TOut),
                    out bytesReturned
                );
            }
        }
    }

    [Guid("415EED2E-98CB-42C2-8F28-B94601074E31")]
    public sealed unsafe partial class IGameInputDispatcher : GameInputComPtr,
        IEquatable<IGameInputDispatcher>
    {
        internal static readonly Guid Iid = new("415EED2E-98CB-42C2-8F28-B94601074E31");

        internal IGameInputDispatcher(IntPtr handle, bool ownsHandle) : base(handle, ownsHandle) { }

        public IGameInputDispatcher Duplicate()
        {
            Marshal.AddRef(handle);
            return new(handle, ownsHandle: true);
        }

        public bool Dispatch(
            uint64_t quotaInMicroseconds
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDispatcher));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint64_t, byte>)vtable[3];

            var result = fnPtr(
                thisPtr,
                quotaInMicroseconds
            );

            return result != 0;
        }

        public HRESULT OpenWaitHandle(
            out HANDLE waitHandle
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputDispatcher));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out HANDLE, HRESULT>)vtable[4];

            var result = fnPtr(
                thisPtr,
                out waitHandle
            );

            return result;
        }

        public bool Equals([NotNullWhen(true)] IGameInputDispatcher? ptr)
            => this == ptr;
    }

    [Guid("FF61096A-3373-4093-A1DF-6D31846B3511")]
    public sealed unsafe partial class IGameInputForceFeedbackEffect : GameInputComPtr,
        IEquatable<IGameInputForceFeedbackEffect>
    {
        internal static readonly Guid Iid = new("FF61096A-3373-4093-A1DF-6D31846B3511");

        internal IGameInputForceFeedbackEffect(IntPtr handle, bool ownsHandle) : base(handle, ownsHandle) { }

        public IGameInputForceFeedbackEffect Duplicate()
        {
            Marshal.AddRef(handle);
            return new(handle, ownsHandle: true);
        }

        public void GetDevice(
            out LightIGameInputDevice device
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out IntPtr, void>)vtable[3];

            fnPtr(
                thisPtr,
                out IntPtr device_handle
            );

            device = new(device_handle, ownsHandle: true);
        }

        public uint32_t GetMotorIndex()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[4];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public float GetGain()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, float>)vtable[5];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public void SetGain(
            float gain
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, float, void>)vtable[6];

            fnPtr(
                thisPtr,
                gain
            );

        }

        public void GetParams(
            out GameInputForceFeedbackParams ffbParams
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputForceFeedbackParams, void>)vtable[7];

            fnPtr(
                thisPtr,
                out ffbParams
            );

        }

        public bool SetParams(
            in GameInputForceFeedbackParams ffbParams
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, in GameInputForceFeedbackParams, byte>)vtable[8];

            var result = fnPtr(
                thisPtr,
                in ffbParams
            );

            return result != 0;
        }

        public GameInputFeedbackEffectState GetState()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputFeedbackEffectState>)vtable[9];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public void SetState(
            GameInputFeedbackEffectState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputFeedbackEffectState, void>)vtable[10];

            fnPtr(
                thisPtr,
                state
            );

        }

        public bool Equals([NotNullWhen(true)] IGameInputForceFeedbackEffect? ptr)
            => this == ptr;

        public bool Equals(LightIGameInputForceFeedbackEffect obj)
            => this == obj;
    }

    public unsafe ref partial struct LightIGameInputForceFeedbackEffect
    {
        internal IntPtr handle;
        private bool ownsHandle;

        public bool IsInvalid => handle == IntPtr.Zero;

        internal LightIGameInputForceFeedbackEffect(IntPtr handle, bool ownsHandle)
        {
            this.handle = handle;
            this.ownsHandle = ownsHandle;
        }

        public void Dispose()
        {
            if (handle != IntPtr.Zero && ownsHandle)
            {
                Marshal.Release(handle);
                handle = IntPtr.Zero;
            }
        }

        public IntPtr DangerousGetHandle() => handle;

        public IGameInputForceFeedbackEffect ToComPtr()
        {
            // Move handle to the new instance
            var handle = this.handle;
            this.handle = IntPtr.Zero;
            return new(handle, ownsHandle);
        }

        public static implicit operator LightIGameInputForceFeedbackEffect(IGameInputForceFeedbackEffect instance)
        {
            return new(instance.DangerousGetHandle(), ownsHandle: false);
        }

        public static bool operator ==(LightIGameInputForceFeedbackEffect left, LightIGameInputForceFeedbackEffect right)
        {
            // GameInput interfaces can be compared directly by pointer for equality
            return left.handle == right.handle;
        }

        public static bool operator ==(IGameInputForceFeedbackEffect? left, LightIGameInputForceFeedbackEffect right)
        {
            return left?.handle == right.handle;
        }

        public static bool operator ==(LightIGameInputForceFeedbackEffect left, IGameInputForceFeedbackEffect? right)
        {
            return left.handle == right?.handle;
        }

        public static bool operator !=(LightIGameInputForceFeedbackEffect left, LightIGameInputForceFeedbackEffect right)
            => !(left == right);

        public static bool operator !=(IGameInputForceFeedbackEffect? left, LightIGameInputForceFeedbackEffect right)
            => !(left == right);

        public static bool operator !=(LightIGameInputForceFeedbackEffect left, IGameInputForceFeedbackEffect? right)
            => !(left == right);

        public readonly bool Equals(LightIGameInputForceFeedbackEffect obj)
            => this == obj;

        public readonly bool Equals(IGameInputForceFeedbackEffect? obj)
            => this == obj;

#pragma warning disable CS0809 // Obsolete member overrides non-obsolete member
        [Obsolete("Equals(object) on LightIGameInputForceFeedbackEffect will always throw an exception. Use the equality operator instead.", true)]
        public override bool Equals(object? obj)
            => throw new NotSupportedException();
#pragma warning restore CS0809

        public override int GetHashCode()
            => handle.GetHashCode();

        public void GetDevice(
            out LightIGameInputDevice device
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out IntPtr, void>)vtable[3];

            fnPtr(
                thisPtr,
                out IntPtr device_handle
            );

            device = new(device_handle, ownsHandle: true);
        }

        public uint32_t GetMotorIndex()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, uint32_t>)vtable[4];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public float GetGain()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, float>)vtable[5];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public void SetGain(
            float gain
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, float, void>)vtable[6];

            fnPtr(
                thisPtr,
                gain
            );

        }

        public void GetParams(
            out GameInputForceFeedbackParams ffbParams
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, out GameInputForceFeedbackParams, void>)vtable[7];

            fnPtr(
                thisPtr,
                out ffbParams
            );

        }

        public bool SetParams(
            in GameInputForceFeedbackParams ffbParams
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, in GameInputForceFeedbackParams, byte>)vtable[8];

            var result = fnPtr(
                thisPtr,
                in ffbParams
            );

            return result != 0;
        }

        public GameInputFeedbackEffectState GetState()
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputFeedbackEffectState>)vtable[9];

            var result = fnPtr(
                thisPtr
            );

            return result;
        }

        public void SetState(
            GameInputFeedbackEffectState state
        )
        {
            ThrowHelper.CheckDisposed(IsInvalid, typeof(IGameInputForceFeedbackEffect));

            var thisPtr = handle;
            var vtable = *(void***)thisPtr;
            var fnPtr = (delegate* unmanaged[Stdcall]<IntPtr, GameInputFeedbackEffectState, void>)vtable[10];

            fnPtr(
                thisPtr,
                state
            );

        }
    }

    #endregion

    #region Callback implementations

    public unsafe partial class IGameInput
    {
        private delegate void GameInputReadingCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr reading
        );

        private delegate void GameInputDeviceCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            uint64_t timestamp,
            GameInputDeviceStatus currentStatus,
            GameInputDeviceStatus previousStatus
        );

        private delegate void GameInputSystemButtonCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            uint64_t timestamp,
            GameInputSystemButtons currentButtons,
            GameInputSystemButtons previousButtons
        );

        private delegate void GameInputKeyboardLayoutCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            uint64_t timestamp,
            uint32_t currentLayout,
            uint32_t previousLayout
        );

#if NET5_0_OR_GREATER
        private static readonly GameInputReadingCallback_NativePtr _GameInputReadingCallbackPtr = &_GameInputReadingCallback;
        private static readonly GameInputDeviceCallback_NativePtr _GameInputDeviceCallbackPtr = &_GameInputDeviceCallback;
        private static readonly GameInputSystemButtonCallback_NativePtr _GameInputSystemButtonCallbackPtr = &_GameInputSystemButtonCallback;
        private static readonly GameInputKeyboardLayoutCallback_NativePtr _GameInputKeyboardLayoutCallbackPtr = &_GameInputKeyboardLayoutCallback;
#else
        private static readonly GameInputReadingCallback_Native _GameInputReadingCallbackDelegate = _GameInputReadingCallback;
        private static readonly GameInputDeviceCallback_Native _GameInputDeviceCallbackDelegate = _GameInputDeviceCallback;
        private static readonly GameInputSystemButtonCallback_Native _GameInputSystemButtonCallbackDelegate = _GameInputSystemButtonCallback;
        private static readonly GameInputKeyboardLayoutCallback_Native _GameInputKeyboardLayoutCallbackDelegate = _GameInputKeyboardLayoutCallback;

        private static readonly GameInputReadingCallback_NativePtr _GameInputReadingCallbackPtr = (GameInputReadingCallback_NativePtr)
            Marshal.GetFunctionPointerForDelegate(_GameInputReadingCallbackDelegate);
        private static readonly GameInputDeviceCallback_NativePtr _GameInputDeviceCallbackPtr = (GameInputDeviceCallback_NativePtr)
            Marshal.GetFunctionPointerForDelegate(_GameInputDeviceCallbackDelegate);
        private static readonly GameInputSystemButtonCallback_NativePtr _GameInputSystemButtonCallbackPtr = (GameInputSystemButtonCallback_NativePtr)
            Marshal.GetFunctionPointerForDelegate(_GameInputSystemButtonCallbackDelegate);
        private static readonly GameInputKeyboardLayoutCallback_NativePtr _GameInputKeyboardLayoutCallbackPtr = (GameInputKeyboardLayoutCallback_NativePtr)
            Marshal.GetFunctionPointerForDelegate(_GameInputKeyboardLayoutCallbackDelegate);
#endif

        public bool RegisterReadingCallback(
            IGameInputDevice? device,
            GameInputKind inputKind,
            object? context,
            GameInputReadingCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterReadingCallback(
                device,
                inputKind,
                _callbacks.MakeCallbackContext(this),
                _GameInputReadingCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterDeviceCallback(
            IGameInputDevice? device,
            GameInputKind inputKind,
            GameInputDeviceStatus statusFilter,
            GameInputEnumerationKind enumerationKind,
            object? context,
            GameInputDeviceCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterDeviceCallback(
                device,
                inputKind,
                statusFilter,
                enumerationKind,
                _callbacks.MakeCallbackContext(this),
                _GameInputDeviceCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterSystemButtonCallback(
            IGameInputDevice? device,
            GameInputSystemButtons buttonFilter,
            object? context,
            GameInputSystemButtonCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterSystemButtonCallback(
                device,
                buttonFilter,
                _callbacks.MakeCallbackContext(this),
                _GameInputSystemButtonCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterKeyboardLayoutCallback(
            IGameInputDevice? device,
            object? context,
            GameInputKeyboardLayoutCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterKeyboardLayoutCallback(
                device,
                _callbacks.MakeCallbackContext(this),
                _GameInputKeyboardLayoutCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

#if NET5_0_OR_GREATER
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
#endif
#if SHARPGAMEINPUT_UNITY
        [AOT.MonoPInvokeCallback(typeof(GameInputReadingCallback_Native))]
#endif
        private static void _GameInputReadingCallback(
            ulong callbackToken,
            void* context,
            IntPtr reading
        )
        {
            IGameInput gameInput = null!;
            try
            {
                gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputReadingCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputReading(reading, false)
                );
            }
            catch (Exception ex)
            {
                CallbackRegistrar<IGameInput>.OnUnhandledCallbackException(gameInput?._callbacks, ex);
            }
        }

#if NET5_0_OR_GREATER
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
#endif
#if SHARPGAMEINPUT_UNITY
        [AOT.MonoPInvokeCallback(typeof(GameInputDeviceCallback_Native))]
#endif
        private static void _GameInputDeviceCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            uint64_t timestamp,
            GameInputDeviceStatus currentStatus,
            GameInputDeviceStatus previousStatus
        )
        {
            IGameInput gameInput = null!;
            try
            {
                gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputDeviceCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentStatus,
                    previousStatus
                );
            }
            catch (Exception ex)
            {
                CallbackRegistrar<IGameInput>.OnUnhandledCallbackException(gameInput?._callbacks, ex);
            }
        }

#if NET5_0_OR_GREATER
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
#endif
#if SHARPGAMEINPUT_UNITY
        [AOT.MonoPInvokeCallback(typeof(GameInputSystemButtonCallback_Native))]
#endif
        private static void _GameInputSystemButtonCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            uint64_t timestamp,
            GameInputSystemButtons currentButtons,
            GameInputSystemButtons previousButtons
        )
        {
            IGameInput gameInput = null!;
            try
            {
                gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputSystemButtonCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentButtons,
                    previousButtons
                );
            }
            catch (Exception ex)
            {
                CallbackRegistrar<IGameInput>.OnUnhandledCallbackException(gameInput?._callbacks, ex);
            }
        }

#if NET5_0_OR_GREATER
        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
#endif
#if SHARPGAMEINPUT_UNITY
        [AOT.MonoPInvokeCallback(typeof(GameInputKeyboardLayoutCallback_Native))]
#endif
        private static void _GameInputKeyboardLayoutCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            uint64_t timestamp,
            uint32_t currentLayout,
            uint32_t previousLayout
        )
        {
            IGameInput gameInput = null!;
            try
            {
                gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputKeyboardLayoutCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentLayout,
                    previousLayout
                );
            }
            catch (Exception ex)
            {
                CallbackRegistrar<IGameInput>.OnUnhandledCallbackException(gameInput?._callbacks, ex);
            }
        }
    }

    #endregion
}
