//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Diagnostics.CodeAnalysis;
using SharpGameInput.Common;

#nullable enable

namespace SharpGameInput.v0
{
    using unsafe GameInputReadingCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // reading
        bool, // hasOverrunOccurred
        void // <return>
    >;

    using unsafe GameInputDeviceCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        ulong, // timestamp
        GameInputDeviceStatus, // currentStatus
        GameInputDeviceStatus, // previousStatus
        void // <return>
    >;

    using unsafe GameInputSystemButtonCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        ulong, // timestamp
        GameInputSystemButtons, // currentState
        GameInputSystemButtons, // previousState
        void // <return>
    >;

    using unsafe GameInputKeyboardLayoutCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        ulong, // timestamp
        uint, // currentLayout
        uint, // previousLayout
        void // <return>
    >;

    public delegate void GameInputReadingCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputReading reading,
        bool hasOverrunOccurred
    );

    public delegate void GameInputDeviceCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        ulong timestamp,
        GameInputDeviceStatus currentStatus,
        GameInputDeviceStatus previousStatus
    );

    public delegate void GameInputSystemButtonCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        ulong timestamp,
        GameInputSystemButtons currentState,
        GameInputSystemButtons previousState
    );

    public delegate void GameInputKeyboardLayoutCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        ulong timestamp,
        uint currentLayout,
        uint previousLayout
    );

    public unsafe partial class IGameInput
    {
        public delegate void GameInputReadingCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr reading,
            bool hasOverrunOccurred
        );

        public delegate void GameInputDeviceCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            GameInputDeviceStatus currentStatus,
            GameInputDeviceStatus previousStatus
        );

        public delegate void GameInputSystemButtonCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            GameInputSystemButtons currentState,
            GameInputSystemButtons previousState
        );

        public delegate void GameInputKeyboardLayoutCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            uint currentLayout,
            uint previousLayout
        );

#if NET5_0_OR_GREATER
        private static readonly GameInputReadingCallback_NativePtr _GameInputReadingCallbackPtr = &_GameInputReadingCallback;
        private static readonly GameInputDeviceCallback_NativePtr _GameInputDeviceCallbackPtr = &_GameInputDeviceCallback;
        private static readonly GameInputSystemButtonCallback_NativePtr _GameInputSystemButtonCallbackPtr = &_GameInputSystemButtonCallback;
        private static readonly GameInputKeyboardLayoutCallback_NativePtr _GameInputKeyboardLayoutCallbackPtr = &_GameInputKeyboardLayoutCallback;
#else
        private static readonly GameInputReadingCallback_Native _GameInputReadingCallbackDelegate = _GameInputReadingCallback;
        private static readonly GameInputDeviceCallback_Native _GameInputDeviceCallbackDelegate = _GameInputDeviceCallback;
        private static readonly GameInputSystemButtonCallback_Native _GameInputSystemButtonCallbackDelegate = _GameInputSystemButtonCallback;
        private static readonly GameInputKeyboardLayoutCallback_Native _GameInputKeyboardLayoutCallbackDelegate = _GameInputKeyboardLayoutCallback;

        private static readonly GameInputReadingCallback_NativePtr _GameInputReadingCallbackPtr = (GameInputReadingCallback_NativePtr)
            System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_GameInputReadingCallbackDelegate);
        private static readonly GameInputDeviceCallback_NativePtr _GameInputDeviceCallbackPtr = (GameInputDeviceCallback_NativePtr)
            System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_GameInputDeviceCallbackDelegate);
        private static readonly GameInputSystemButtonCallback_NativePtr _GameInputSystemButtonCallbackPtr = (GameInputSystemButtonCallback_NativePtr)
            System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_GameInputSystemButtonCallbackDelegate);
        private static readonly GameInputKeyboardLayoutCallback_NativePtr _GameInputKeyboardLayoutCallbackPtr = (GameInputKeyboardLayoutCallback_NativePtr)
            System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_GameInputKeyboardLayoutCallbackDelegate);
#endif

        public bool RegisterReadingCallback(
            IGameInputDevice? device,
            GameInputKind inputKind,
            float analogThreshold,
            object? context,
            GameInputReadingCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterReadingCallback(
                device,
                inputKind,
                analogThreshold,
                _callbacks.MakeCallbackContext(this),
                _GameInputReadingCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterDeviceCallback(
            IGameInputDevice? device,
            GameInputKind inputKind,
            GameInputDeviceStatus statusFilter,
            GameInputEnumerationKind enumerationKind,
            object? context,
            GameInputDeviceCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterDeviceCallback(
                device,
                inputKind,
                statusFilter,
                enumerationKind,
                _callbacks.MakeCallbackContext(this),
                _GameInputDeviceCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterSystemButtonCallback(
            IGameInputDevice? device,
            GameInputSystemButtons buttonFilter,
            object? context,
            GameInputSystemButtonCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterSystemButtonCallback(
                device,
                buttonFilter,
                _callbacks.MakeCallbackContext(this),
                _GameInputSystemButtonCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterKeyboardLayoutCallback(
            IGameInputDevice? device,
            object? context,
            GameInputKeyboardLayoutCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterKeyboardLayoutCallback(
                device,
                _callbacks.MakeCallbackContext(this),
                _GameInputKeyboardLayoutCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

#if NET5_0_OR_GREATER
        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
#endif
#if UNITY_STANDALONE
        [AOT.MonoPInvokeCallback(typeof(ReadingCallback_Native))]
#endif
        private static void _GameInputReadingCallback(
            ulong callbackToken,
            void* context,
            IntPtr reading,
            bool hasOverrunOccurred
        )
        {
            try
            {
                var gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputReadingCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputReading(reading, true),
                    hasOverrunOccurred
                );
            }
            catch (Exception ex)
            {
                OnUnhandledCallbackException(ex);
            }
        }

#if NET5_0_OR_GREATER
        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
#endif
#if UNITY_STANDALONE
        [AOT.MonoPInvokeCallback(typeof(ReadingCallback_Native))]
#endif
        private static void _GameInputDeviceCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            GameInputDeviceStatus currentStatus,
            GameInputDeviceStatus previousStatus
        )
        {
            try
            {
                var gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputDeviceCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentStatus,
                    previousStatus
                );
            }
            catch (Exception ex)
            {
                OnUnhandledCallbackException(ex);
            }
        }

#if NET5_0_OR_GREATER
        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
#endif
#if UNITY_STANDALONE
        [AOT.MonoPInvokeCallback(typeof(ReadingCallback_Native))]
#endif
        private static void _GameInputSystemButtonCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            GameInputSystemButtons currentState,
            GameInputSystemButtons previousState
        )
        {
            try
            {
                var gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputSystemButtonCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentState,
                    previousState
                );
            }
            catch (Exception ex)
            {
                OnUnhandledCallbackException(ex);
            }
        }

#if NET5_0_OR_GREATER
        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
#endif
#if UNITY_STANDALONE
        [AOT.MonoPInvokeCallback(typeof(ReadingCallback_Native))]
#endif
        private static void _GameInputKeyboardLayoutCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            uint currentLayout,
            uint previousLayout
        )
        {
            try
            {
                var gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputKeyboardLayoutCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentLayout,
                    previousLayout
                );
            }
            catch (Exception ex)
            {
                OnUnhandledCallbackException(ex);
            }
        }
    }
}