//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Diagnostics.CodeAnalysis;
using SharpGameInput.Common;

#nullable enable

namespace SharpGameInput.v0
{
    using unsafe ReadingCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // reading
        bool, // hasOverrunOccurred
        void // <return>
    >;

    using unsafe DeviceCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        ulong, // timestamp
        GameInputDeviceStatus, // currentStatus
        GameInputDeviceStatus, // previousStatus
        void // <return>
    >;

    using unsafe SystemButtonCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        ulong, // timestamp
        GameInputSystemButtons, // currentState
        GameInputSystemButtons, // previousState
        void // <return>
    >;

    using unsafe KeyboardLayoutCallback_NativePtr = delegate* unmanaged[Stdcall]<
        ulong, // callbackToken
        void*, // context
        IntPtr, // device
        ulong, // timestamp
        uint, // currentLayout
        uint, // previousLayout
        void // <return>
    >;

    public delegate void GameInputReadingCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputReading reading,
        bool hasOverrunOccurred
    );

    public delegate void GameInputDeviceCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        ulong timestamp,
        GameInputDeviceStatus currentStatus,
        GameInputDeviceStatus previousStatus
    );

    public delegate void GameInputSystemButtonCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        ulong timestamp,
        GameInputSystemButtons currentState,
        GameInputSystemButtons previousState
    );

    public delegate void GameInputKeyboardLayoutCallback(
        LightGameInputCallbackToken callbackToken,
        object? context,
        LightIGameInputDevice device,
        ulong timestamp,
        uint currentLayout,
        uint previousLayout
    );

    public unsafe partial class IGameInput
    {
        public delegate void ReadingCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr reading,
            bool hasOverrunOccurred
        );

        public delegate void DeviceCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            GameInputDeviceStatus currentStatus,
            GameInputDeviceStatus previousStatus
        );

        public delegate void SystemButtonCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            GameInputSystemButtons currentState,
            GameInputSystemButtons previousState
        );

        public delegate void KeyboardLayoutCallback_Native(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            uint currentLayout,
            uint previousLayout
        );

#if NET5_0_OR_GREATER
        private static readonly ReadingCallback_NativePtr _ReadingCallbackPtr = &_ReadingCallback;
        private static readonly DeviceCallback_NativePtr _DeviceCallbackPtr = &_DeviceCallback;
        private static readonly SystemButtonCallback_NativePtr _SystemButtonCallbackPtr = &_SystemButtonCallback;
        private static readonly KeyboardLayoutCallback_NativePtr _KeyboardLayoutCallbackPtr = &_KeyboardLayoutCallback;
#else
        private static readonly ReadingCallback_Native _ReadingCallbackDelegate = _ReadingCallback;
        private static readonly DeviceCallback_Native _DeviceCallbackDelegate = _DeviceCallback;
        private static readonly SystemButtonCallback_Native _SystemButtonCallbackDelegate = _SystemButtonCallback;
        private static readonly KeyboardLayoutCallback_Native _KeyboardLayoutCallbackDelegate = _KeyboardLayoutCallback;

        private static readonly ReadingCallback_NativePtr _ReadingCallbackPtr = (ReadingCallback_NativePtr)
            System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_ReadingCallbackDelegate);
        private static readonly DeviceCallback_NativePtr _DeviceCallbackPtr = (DeviceCallback_NativePtr)
            System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_DeviceCallbackDelegate);
        private static readonly SystemButtonCallback_NativePtr _SystemButtonCallbackPtr = (SystemButtonCallback_NativePtr)
            System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_SystemButtonCallbackDelegate);
        private static readonly KeyboardLayoutCallback_NativePtr _KeyboardLayoutCallbackPtr = (KeyboardLayoutCallback_NativePtr)
            System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(_KeyboardLayoutCallbackDelegate);
#endif

        public bool RegisterReadingCallback(
            IGameInputDevice? device,
            GameInputKind inputKind,
            float analogThreshold,
            object? context,
            GameInputReadingCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterReadingCallback(
                device,
                inputKind,
                analogThreshold,
                _callbacks.MakeCallbackContext(this),
                _ReadingCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterDeviceCallback(
            IGameInputDevice? device,
            GameInputKind inputKind,
            GameInputDeviceStatus statusFilter,
            GameInputEnumerationKind enumerationKind,
            object? context,
            GameInputDeviceCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterDeviceCallback(
                device,
                inputKind,
                statusFilter,
                enumerationKind,
                _callbacks.MakeCallbackContext(this),
                _DeviceCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterSystemButtonCallback(
            IGameInputDevice? device,
            GameInputSystemButtons buttonFilter,
            object? context,
            GameInputSystemButtonCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterSystemButtonCallback(
                device,
                buttonFilter,
                _callbacks.MakeCallbackContext(this),
                _SystemButtonCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

        public bool RegisterKeyboardLayoutCallback(
            IGameInputDevice? device,
            object? context,
            GameInputKeyboardLayoutCallback callbackFunc,
            [NotNullWhen(true)] out GameInputCallbackToken? callbackToken,
            out int result
        )
        {
            ThrowHelper.CheckNull(callbackFunc);

            using var scope = _callbacks.StartRegisteringCallback(callbackFunc, context);
            result = _RegisterKeyboardLayoutCallback(
                device,
                _callbacks.MakeCallbackContext(this),
                _KeyboardLayoutCallbackPtr,
                out ulong token
            );

            bool success = scope.Finish(result, token);
            callbackToken = success ? new(this, token) : null;
            return success;
        }

#if NET5_0_OR_GREATER
        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
#endif
#if UNITY_STANDALONE
        [AOT.MonoPInvokeCallback(typeof(ReadingCallback_Native))]
#endif
        private static void _ReadingCallback(
            ulong callbackToken,
            void* context,
            IntPtr reading,
            bool hasOverrunOccurred
        )
        {
            try
            {
                var gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputReadingCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputReading(reading, true),
                    hasOverrunOccurred
                );
            }
            catch (Exception ex)
            {
                OnUnhandledCallbackException(ex);
            }
        }

#if NET5_0_OR_GREATER
        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
#endif
#if UNITY_STANDALONE
        [AOT.MonoPInvokeCallback(typeof(ReadingCallback_Native))]
#endif
        private static void _DeviceCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            GameInputDeviceStatus currentStatus,
            GameInputDeviceStatus previousStatus
        )
        {
            try
            {
                var gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputDeviceCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentStatus,
                    previousStatus
                );
            }
            catch (Exception ex)
            {
                OnUnhandledCallbackException(ex);
            }
        }

#if NET5_0_OR_GREATER
        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
#endif
#if UNITY_STANDALONE
        [AOT.MonoPInvokeCallback(typeof(ReadingCallback_Native))]
#endif
        private static void _SystemButtonCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            GameInputSystemButtons currentState,
            GameInputSystemButtons previousState
        )
        {
            try
            {
                var gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputSystemButtonCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentState,
                    previousState
                );
            }
            catch (Exception ex)
            {
                OnUnhandledCallbackException(ex);
            }
        }

#if NET5_0_OR_GREATER
        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
#endif
#if UNITY_STANDALONE
        [AOT.MonoPInvokeCallback(typeof(ReadingCallback_Native))]
#endif
        private static void _KeyboardLayoutCallback(
            ulong callbackToken,
            void* context,
            IntPtr device,
            ulong timestamp,
            uint currentLayout,
            uint previousLayout
        )
        {
            try
            {
                var gameInput = CallbackRegistrar<IGameInput>.ContextToInstance(context);
                var (_callbackFunc, callbackContext) = gameInput._callbacks.GetCallback(callbackToken);
                var callbackFunc = (GameInputKeyboardLayoutCallback)_callbackFunc;

                callbackFunc(
                    new LightGameInputCallbackToken(gameInput, callbackToken),
                    callbackContext,
                    new LightIGameInputDevice(device, false),
                    timestamp,
                    currentLayout,
                    previousLayout
                );
            }
            catch (Exception ex)
            {
                OnUnhandledCallbackException(ex);
            }
        }
    }
}