<Project>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12</LangVersion>
    <DefineConstants>$(DefineConstants);GAMEINPUT_v$(GameInputApiVersion)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Source/SharpGameInput.v$(GameInputApiVersion).csproj" />
    <Using Include="SharpGameInput.v$(GameInputApiVersion)" />

    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.205">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Condition="'$(TargetFramework)' == 'net48'" Include="System.Memory" Version="4.5.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)/**/*.cs" LinkBase="Common" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)/NativeMethods.txt" LinkBase="Common" />
  </ItemGroup>

</Project>