<Project>

  <!-- This is not a proper project file because SharpGameInput is designed to be a
    single .dll with no dependencies. This design makes it easy to use in projects that
    might not have proper access to NuGet, e.g. Unity. -->

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0-windows</TargetFrameworks>
    <LangVersion>12</LangVersion> <!-- For function pointers, `scoped`, and `using` type aliases -->
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>SharpGameInput.v$(GameInputApiVersion)</AssemblyName>
    <AssemblyTitle>$(AssemblyName)</AssemblyTitle>
    <Product>$(AssemblyName)</Product>
    <Version>0.2.0</Version>
    <Description>C# interop bindings for GameInput v$(GameInputApiVersion).</Description>
    <Authors>Nathan Hurst</Authors>
    <Copyright>Copyright (c) 2024 $(Authors)</Copyright>
    <RepositoryUrl>https://github.com/TheNathannator/SharpGameInput</RepositoryUrl>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.205">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="PolySharp" Version="1.14.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)/*.cs" LinkBase="Common" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)/NativeMethods.txt" LinkBase="Common" />
  </ItemGroup>

</Project>